//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.DB_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoCurso
    {
        public long IdAlumnoCurso { get; set; }
        public long AlumnoId { get; set; }
        public long CursoId { get; set; }
        public string Nota { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
